version: "3.1"
services:
  loopback:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: 'America/Sao_Paulo'
      DB_HOST: 'loopback-database'
      DB_SSL: 'false'
      DB_PORT: 5432
      DB_USER: 'biotech'
      DB_PASSWORD: 'biotech'
      DB_DATABASE: 'biotech'
      DB_SCHEMA: 'biotech_schema'
      PORT: 3000
    networks:
      - backend
    ports:
      - 3000:3000
    restart: always
    container_name: loopback

  loopback-database:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      TZ: 'America/Sao_Paulo'
      POSTGRES_USER: biotech
      POSTGRES_PASSWORD: biotech
      POSTGRES_DB: biotech
    ports:
      - 54323:5432
    container_name: loopback-database

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8085:80
    environment:
      TZ: 'America/Sao_Paulo'
      PGADMIN_DEFAULT_EMAIL: 'biotech@biotech.com.br'
      PGADMIN_DEFAULT_PASSWORD: 'biotech'
    networks:
      - backend
    container_name: loopback-pgadmin

volumes:
  pgdata:
    # name: pgdata

networks:
  backend:
    driver: bridge
    # name: backend
    # labels:
    #   - "com.example.description=Bio Tech Api"
    #   - "com.example.department=Gym"
